### ISSUE TITLE
Nmap like ip address specification

### ISSUE THREAD

**Issue by bytebutcher** [oldboy21/SMBSR#1]
Hi there!

i've found your tool via kitploit and saw that your tool is working with IP addresses.

I've lately written a tool which takes an nmap-like ip address format and returns the individual ip addresses for further processing.

Since it is quite easy to integrate you may be interested in using it:

https://github.com/bytebutcher/ipranger

Best,
Thomas

**Comment by oldboy21** [comment]
Cool i ll take a look at it 
cheers
