### ISSUE TITLE
CIDR notation seems to be broken

### ISSUE THREAD

**Issue by Mi-Al** [oldboy21/SMBSR#2]
Hello! I try to scan the range 192.168.1.0/24:

`sudo ./smbsr.py -IP 192.168.1.0/24 -word-list-path /home/mial/test/list.txt -masscan
`

I get an error:

> masscan failed with error: 'FAIL: target IP address list empty\n [hint] try something like "--range 10.0.0.0/8"\n [hint] try something like "--range 192.168.0.100-192.168.0.200"\n'

I try the **--range** option:

`sudo ./smbsr.py --range 192.168.1.0/24 -word-list-path /home/mial/test/list.txt -masscan
`

Then I get an error:

> smbsr.py: error: unrecognized arguments: --range 192.168.1.0/24

**Comment by oldboy21** [comment]
can't replicate the error, you sure you running the last version? pushed some minor changes last week about how IP ranges are handled

**Comment by Mi-Al** [comment]
Now it is fine. Thank you!
